### ISSUE TITLE
Some questions about ruby_aws_cpi/packaging

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry-incubator/bosh-aws-cpi-release#32]
Should this line be `set +e` or `set -e`?
https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/packages/ruby_aws_cpi/packaging#L13

Should the part be moved into the block of `tar xzf`? 
https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/packages/ruby_aws_cpi/packaging#L19-L22

IMHO, the error of "Cannot install yaml" can be caught only if `+e` is set.
Thanks.

**Comment by dpb587-pivotal** [comment]
`set -e` will make the subshell fail immediately if there's an error. The `if [[ $? != 0 ]]` should then catch the result of the subshell. Doing `set +x` would make commands continue if they fail.

However, I think maybe line 1's `set -e` is causing a different behavior than expected. I don't think it'd reach the conditional where it prints `Cannot install yaml` sorts of nice messages.

Maybe someone from the CPI team has a better idea.

**Comment by ljfranklin** [comment]
Yep, looks like a bug. I'll throw in a chore / bug to do a little bash clean-up. Thanks for the heads up!

**Comment by flawedmatrix** [comment]
Closing this issue, since this should be fixed with:
https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/commit/fb3e18944b7105305a8c2227eaffdaea78f06d03
https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/commit/33e96eba27f422bfb3c1e51d4cfd1ec2ae59ec92

Thanks for pointing us to this!
