### ISSUE TITLE
AWS Tagging limitation

### ISSUE THREAD

**Issue by hhercules** [cloudfoundry-incubator/bosh-aws-cpi-release#33]
I have some questions about tagging on AWS. 

1. Allowing for tagging parameters we can pass in to instances that will be created by bosh. This way I don't have to go back and tag items created post instance or volume creation. 

2. Instead of creating several tags that eat into the tag limit count combining bosh specific tags. ie. Key Name="Bosh Tags", Values of Tags="bosh:job:index:something;else".  This way would use up 1 tag instead of 5 for example:

```
"Tags": [
        {
            "Value": "router-partition-50386dce3e87b8779d04/1",
            "Key": "Name"
        },
        {
            "Value": "cf-c563a8009d0819f5d361",
            "Key": "deployment"
        },
        {
            "Value": "p-bosh-1e0844c6e06194193362",
            "Key": "director"
        },
        {
            "Value": "1",
            "Key": "index"
        },
        {
            "Value": "router-partition-50386dce3e87b8779d04",
            "Key": "job"
        } 
       ]
```

**Comment by cppforlife** [comment]
Related to https://github.com/cloudfoundry/bosh/issues/936

**Comment by cppforlife** [comment]
@hhercules for your use case do you want custom tags to be scoped to the deployment or director?

**Comment by hhercules** [comment]
Deployment. The director here was just and example.

**Comment by cppforlife** [comment]
@hhercules any concrete examples of what tags you would set at a deployment level?

**Comment by hhercules** [comment]
Glad you asked :)

1.      Company Code  (with a space between ‘Company’ and ‘Code’, numeric, 4 digits): 1234
2.      Cost Center (with a space between ‘Cost’ and ‘Center’, numeric, 6 digits): 123456
3.      Name (system name / descriptive name of system or ‘deployment node’): cf_bosh_qa (This can be set by system)
4.    Application Metadata   (”APP”:”ENV”:”TIER”:”EMAIL”)
        A.   APP (name of the application ecosystem)
       B.    ENV (development, QA, stage, production, DR)
       C.    TIER (web, application, database) 
       D.    Email (contact email who created resources)
 
#4 is a compound tag named, "Application Metadata", and value for example "MyApp:Production:AppTier:BlueTeam@MyCompany.com".

**Comment by cppforlife** [comment]
@hhercules would you be interested in making a PR to the Director to add support for specifying deployment level tags?

**Comment by hhercules** [comment]
How would I go about doing that?

**Comment by cppforlife** [comment]
@hhercules I think first step is to agree on how configuration would look like in the deployment manifest. Following is a pretty good start imho given your comment above:

```yaml
---
name: my-deployment

# User can specify any key value pair
tags:
  "Company Code": "1234"
  "Cost Center": "123456"
  "System Name": "cf_bosh_qa"
  "Application Metadata": "MyApp:Production:AppTier:BlueTeam@MyCompany.com"

instance_groups:
- name: something
  instances: 10
  ...

update:
  max_in_flight: 10
  canaries: 10
  ...
```

Tags section is set at the deployment level and all VMs associated with that deployment will have all of these tags applied plus whatever tags are generically applied by the Director. I think as a first step having more terse tags should be out of scope.

Given that the tags are being applied by the Director this would be a change to the https://github.com/cloudfoundry/bosh/tree/master/bosh-director (Director source). It looks like that https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/bosh-director/lib/bosh/director/vm_metadata_updater.rb is the place to change for which information is sent to the CPI (set_vm_metadata CPI call does the actual tagging). It appears that it has access to the instance and instance's deployment so assuming that somehow these tags make it onto deployment you can either modify instance class to have some method that returns a list of its deployment tags (instance.tags => {"deployment" => ..., plus other tags}) or just access deployment directly (instance.deployment.tags => {...}).

Now to get tags onto deployment object you will have to modify deployment spec parser which is responsible for converting raw manifest hash into deployment object: https://github.com/cloudfoundry/bosh/blob/93a2522b3a6a58cc3d24f6ea10a9dba0a9a421bb/bosh-director/lib/bosh/director/deployment_plan/deployment_spec_parser.rb. Check out parse_update section that does very similar thing.

Also right before making cloud.set_vm_metadata call we should probably turn all values into strings so that CPIs dont have to worry about non-string types. Keeps developing/maintaining CPIs easier.

Of course while making these changes make sure to add appropriate unit tests in associated _test.rb files.

One caveat after implementing this change though is that it would not cover Director VM itself since that's deployed by bosh-init at this point. That probably requires a bit more thinking in how to make this easier, but I dont think it affects your use case. There is also another optimization we could add that allows to set tags for all deployments via runtime config so that in this example you wouldnt have to repeat "Company Code" tag in each deployment...

Feel free to visit #bosh in slack.cloudfoundry.org channel to discuss more details in real-time if you prefer. We could even screen share for a bit (US east/west coast times typically). 

Let me know what you think about proposed changes above...

Cheers.

**Comment by dpb587-pivotal** [comment]
Another idea for a deployment tag is a story/issue/task ID - then a bot could more easily check to see if a story has been finished, but the deployment was forgotten and vms abandoned.

**Comment by cppforlife** [comment]
@hhercules v258 bosh release adds `tags` section to the deployment manifest for arbitrary tags. we'll document it shortly. short example:

```
instance_groups:  [...]

tags:
  bu: sales
  env: prod
```

**Comment by zmb3** [comment]
Is this documented yet?  I don't see anything in the v258 release notes or bosh.io/docs
@cppforlife

**Comment by cppforlife** [comment]
not yet. will be documented shortly.

**Comment by cppforlife** [comment]
@zmb3 https://bosh.io/docs/manifest-v2.html#tags & https://bosh.io/docs/runtime-config.html#tags

**Comment by zmb3** [comment]
Awesome. Thanks for the quick turn around!
