### ISSUE TITLE
Allow the use of STS generated credentials

### ISSUE THREAD

**Issue by jrrickard** [cloudfoundry-incubator/bosh-aws-cpi-release#60]
We make use of linked accounts and pretty strictly disallow the creation of "local" IAM users, so we really need to make use of the sts assume-role capability which results in:

SecretAccessKey,
SessionToken,
AccessKeyId

Doesn't look like I can currently make use of this approach since src/bosh_aws_cpi/lib/cloud/aws/cloud.rb does a Aws::Credentials.new(access_key, secret_access_key) call. The library should support using the session token as well, per: 
http://docs.aws.amazon.com/sdkforruby/api/Aws/Credentials.html

Not sure what the operational implications are though, so maybe not the best approach.

**Comment by cppforlife** [comment]
@jrrickard would iam instance profiles help you? http://bosh.io/docs/aws-iam-instance-profiles.html

**Comment by karampok** [comment]
Greetings!
 I am trying to set up a bosh director in AWS and I am getting the following error
`was not able to validate the provided access credentials`. 

It seems that we have enabled the MFA in AWS, which blocks many calls unless is MFA authenticated.  I had to do something like that in order to make terraform work
```
export AWS_MFA_Device=XXX
function aws-mfa() {
  unset AWS_SECRET_ACCESS_KEY; unset AWS_ACCESS_KEY_ID
  ret=$(aws sts get-session-token --serial-number $AWS_MFA_Device --token-code $1)
  export AWS_ACCESS_KEY_ID=$(echo $ret| jq -r '.Credentials.AccessKeyId')
  export AWS_SESSION_TOKEN=$(echo $ret| jq -r '.Credentials.SessionToken')
  export AWS_SECRET_ACCESS_KEY=$(echo $ret| jq -r '.Credentials.SecretAccessKey')
}
```

Given that the cpi does not accept the session token, i think it is the same issue?
What do you think? Any plan to schedule it?

Thanks

**Comment by cdutra** [comment]
@karampok The maximum time for a session token is 36 hours. You would have to update the token code every 36 hours in order for the aws client to retrieve a new valid token.
Is that a desirable use case for you?

**Comment by karampok** [comment]
Hi, for my development use case this is the only option. I have only access to STS generated credentials.  Will something stop working if the aws client has expired credentials?

**Comment by keymon** [comment]
I think this is a quite important and necessary change.

Using STS temporary credentials is a recommended practice, and usually enforced everywhere. It is used not only for security, but also to implement delegation using roles and permissions.

The instances profiles is one way of getting temporary credentials from one machine.

But there are multiple cases that  you have to use environment variables. For instance, when using locally the CPI for when deploying a new environment using `bosh create-env`: The user must would assume role using MFA, and then deploy the application. 

In some places they even block using the metadata endpoint to get instance profile credentials, as it might be a security thread when running containerised environments (e.g. running an automated deployment on concourse). 

Adding support for this should be a small and risk-less change, it would allow the CPI fully support AWS auth mechanism and unblock users to use.

**Comment by keymon** [comment]
Regarding the implementation, I would say this should be implemented as follows:

 1. add the optional param `aws_session_token`, to be used together with `access_key_id` , ` secret_access_key` when calling http://docs.aws.amazon.com/sdkforruby/api/Aws/Credentials.html#initialize-instance_method in https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/703149c7f83bac29427995299d8c19a0d9c04557/src/bosh_aws_cpi/lib/cloud/aws/config.rb#L32. If ` session_token` is not provided, we pass nil.

 2. Extend the logic in https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/703149c7f83bac29427995299d8c19a0d9c04557/src/bosh_aws_cpi/lib/cloud/aws/config.rb#L34 so that it would check if the environment variables are set. If they are, it would use them, otherwise it would try with instance profile.

I am not sure how the official ruby library deals with the credential in environment variables, but it theory it does: http://docs.aws.amazon.com/sdkforruby/api/. Maybe we should have a look.

This approach would cover all the use cases:

 * The option 1, would allow pass the credentials and variables during interpolation: `bosh create-env -v session_token=${AWS_SESSION_TOKEN} -v access_key_id=${AWS_ACCESS_KEY_ID}  and -v  secret_access_key=${AWS_SECRET_KEY}`. This is great to use in automated scripts with bosh-lite 

 * The option 2 would allow define environment variables in actual deployments or other uses of the CPI.

**Comment by cppforlife** [comment]
available in v68.
