### ISSUE TITLE
fail fast if another instance already using IP address

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bosh-aws-cpi-release#69]
When bosh unknowingly selects an IP address for a `create_vm` that is already in use, the bosh director will call out to `create_vm` and just block. `bosh cancel-task` won't stop it. You just have to wait and stew.

Could we update `create_vm` to first quickly double check with AWS that the selected IP address is not already in use and fail fast? Then the operator can update their cloud-config's reserved list and start again.

**Comment by drnic** [comment]
Hmm, there is some specific logic + comments that suggest that an IP address that's already in use could mean that we need to wait for it to be released.

https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb#L140-L146

**Comment by drnic** [comment]
That being the case, is it possible or out of the question for `bosh cancel-task` to more quickly cancel the `create_vm` call to the CPI?

**Comment by cdutra** [comment]
@drnic We've seen issues of AWS SDK retrying by itself by not releasing the IP address in time. I don't know if this is specifically what is happening in your environment. Unfortunately we weren't able to reproduce but would be happy to do more investigation around that if necessary.

I don't know details about `cancel-task`. @dpb587 Any ideas?

**Comment by dpb587-pivotal** [comment]
In @drnic's case it seems the environment is shared with non-bosh-managed instances and they have difficulty keeping the cloud-config's network `reserved` section in sync with real world settings.

There's currently no way to propagate a task cancellation message to the externally-executed CPI. In theory, director could propagate a linux signal like `INT` to an executed CPI process to hint it should exit ASAP, but that might result in a lot of extra complexity for CPIs and director. I'm not sure that would be worth it.

Historically, outside of BOSH, I've seen delays of IPs being freed in from a terminated VM in the network side of EC2, like @cdutra suggests. Assuming that IP propagation delay is still an issue in modern AWS infrastructure, an alternative to constant, long retries would be for the CPI to follow up the failure by querying all instances to filter for the claimed IP address. Since terminated instances don't have IPs (the IP propagation delay is separate, iirc), there should be no instances returned; if there are instances found (and in started state?) the CPI could fail the `create_vm` quickly knowing there's no future change likely.

**Comment by drnic** [comment]
I'll close this ticket as I don't think there are any cpi specific fixes to the bigger issues. thanks for the discussion.
